#!/bin/bash  

#------------------------------------------------------------------------------
# Basic Ubuntu Package.
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Configuration.
#------------------------------------------------------------------------------
message="Install Basic Ubuntu packages"
data_dir=$HOME/Desktop/data
hub_dir=$data_dir/hub
auth_dir=$data_dir/auth
userhome=/home/$SUDO_USER

#------------------------------------------------------------------------------
# Packages.
#------------------------------------------------------------------------------
packages=(

curl
openssl

fcitx-table-cangjie3
fcitx-table-quick3
fcitx-table-cantonhk

dconf-tools
compizconfig-settings-manager

emacs
emacs-goodies-el

tree
sqliteman
md5deep
rar
unrar
gksu
vlc
youtube-dl
okular

)

#------------------------------------------------------------------------------
# Operation - ~/.bashrc.
#------------------------------------------------------------------------------
function modify_bashrc
{
    bashrc=$HOME/.bashrc
    id='User Customization by Hub'
    done=`cat $bashrc | grep "$id"`
    if [ ${#done} == 0 ]; then
        content="\n\n# $id.\n. $hub_dir/config/bashrc\n\n"
        printf "$content" >> $bashrc
    fi
    . $bashrc
}

#------------------------------------------------------------------------------
# Operation - SSL key (used at least by Jupyter).
#------------------------------------------------------------------------------
function create_ssl_key
{
    path=$auth_dir/cert.pem
    keypath=$auth_dir/cert.key
    options='-newkey rsa:4096 -nodes -sha512 -x509 -days 3650 -nodes'
    mkdir -p $auth_dir
    openssl req $options -out $path -keyout $keypath
    transfer_access $auth_dir
    chmod go= $keypath
}

#------------------------------------------------------------------------------
# Operation - Dropbox.
#------------------------------------------------------------------------------
function install_dropbox
{
    # Configuration.
    packages=( nautilus-dropbox )
    url=https://www.dropbox.com/download?plat=lnx.x86_64

    # Operation.    
    cd $userhome && wget -O - $url | tar xzf -         # Install dropbox.
    $userhome/.dropbox-dist/dropboxd &                 # Run dropbox daemon.
    ln -s $userhome/Dropbox $userhome/Desktop/dropbox  # Create desktop link.
    aptget ${packages[@]}                              # Install nautilus one.
}

#------------------------------------------------------------------------------
# Operation.
#------------------------------------------------------------------------------
print_message "$message"
aptget ${packages[@]}
modify_bashrc
create_ssl_key
install_dropbox


