#!/bin/bash  

#------------------------------------------------------------------------------
# Python.
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Configuration.
#------------------------------------------------------------------------------
message='Install Python 2 and 3'
pip_conf=''
#pip_conf='--upgrade'
#pip_conf='--upgrade --force-reinstall --ignore-installed'
print_message "$message"

#------------------------------------------------------------------------------
# Utility.
#------------------------------------------------------------------------------
function pipinstall()
{
    pip$1 install $pip_conf "${@:2}"
}

#------------------------------------------------------------------------------
# Packages.
#------------------------------------------------------------------------------
packages=(

python-setuptools
python-pip
python-wheel
python-numpydoc
python-seaborn

python3
python3-dev
python3-doc
python3-setuptools
python3-pip
python3-wheel
python3-tables
python3-sphinx
python3-numpydoc
python3-nose
python3-coverage
python3-yaml
python3-dateutil
python3-pandas
python3-scipy
python3-oauth2client
python3-seaborn

)

pip2packages=(

pydataset
pytz==2013b
statsmodels

)

pip3packages=(

pydataset
pytz==2013b
swigibpy
gspread
statsmodels

)

#------------------------------------------------------------------------------
# Operation.
#------------------------------------------------------------------------------
aptget ${packages[@]}

pip install --upgrade pip
pipinstall 2 ${pip2packages[@]}

pip3 install --upgrade pip
pipinstall 3 ${pip3packages[@]}

