#!/bin/bash  

#------------------------------------------------------------------------------
# Python.
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Configuration.
#------------------------------------------------------------------------------
message='Install Python 2 and 3'
pip_conf='--upgrade --force-reinstall --ignore-installed'
#pip_conf='--upgrade'
print_message "$message"

#------------------------------------------------------------------------------
# Python.
#------------------------------------------------------------------------------
packages=(

python-setuptools
python-pip
python-wheel
python-numpydoc

)
aptget ${packages[@]}

#------------------------------------------------------------------------------
# Python.
#------------------------------------------------------------------------------
packages=(

python3
python3-dev
python3-doc
python3-setuptools
python3-pip
python3-wheel
python3-tables
python3-sphinx
python3-numpydoc
python3-nose
python3-coverage
python3-yaml
python3-dateutil
python3-pandas
python3-scipy

)
aptget ${packages[@]}

#------------------------------------------------------------------------------
# Pip.
#------------------------------------------------------------------------------
packages=(

pytz==2013b
jupyter

)
pip install --upgrade pip
pip install $pip_conf ${packages[@]}

#------------------------------------------------------------------------------
# Pip3.
#------------------------------------------------------------------------------
packages=(

pytz==2013b
jupyter
swigibpy

)
pip3 install --upgrade pip
pip3 install $pip_conf ${packages[@]}

