#!/bin/bash  

#------------------------------------------------------------------------------
# Samba.
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Configuration.
#------------------------------------------------------------------------------
userhome=/home/$SUDO_USER
filename=smb.conf
src_path=$userhome/Desktop/data/local/$filename
dest_path=/etc/samba/$filename
message="Configure Samba"

#------------------------------------------------------------------------------
# Operation.
#------------------------------------------------------------------------------
smbpasswd -a $SUDO_USER
mv -n $dest_path $dest_path.default
rm $dest_path
ln -s $src_path $dest_path
service smbd restart

